client_id: 3MVG9yZ.WNe6byQCfReoi9ffoQDpgw7KQULGspvW1E641rwR0xXbtd80ubHBNpWj8GpbvOo4E28146_6y3QKa
client_secret: 7779371446049751581
username: mike.malloy.2004@gmail.com
password: makeithappen2012GVBxaILWbJ5fqJ7KXIl9YWf3
debugging: true
